name: hera
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - libffi=3.4.2
  - libsqlite=3.40.0
  - libzlib=1.2.13
  - ncurses=6.3
  - openssl=3.0.7
  - pip=22.3.1
  - python=3.9.15
  - readline=8.1.2
  - setuptools=65.6.3
  - tk=8.6.12
  - tzdata=2022g
  - wheel=0.38.4
  - xz=5.2.6
  - pip:
    - argo-workflows==6.3.5
    - black==22.12.0
    - cachetools==5.2.1
    - certifi==2022.12.7
    - charset-normalizer==3.0.1
    - click==8.1.3
    - commonmark==0.9.1
    - google-auth==2.16.0
    - hera-workflows==4.3.1
    - idna==3.4
    - isort==5.11.4
    - kubernetes==25.3.0
    - mypy-extensions==0.4.3
    - oauthlib==3.2.2
    - pathspec==0.10.3
    - platformdirs==2.6.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygments==2.14.0
    - python-dateutil==2.8.2
    - pytz==2022.7
    - pyyaml==6.0
    - requests==2.28.2
    - requests-oauthlib==1.3.1
    - rich==13.0.1
    - rsa==4.9
    - six==1.16.0
    - tomli==2.0.1
    - typer==0.7.0
    - typing-extensions==4.4.0
    - urllib3==1.26.14
    - websocket-client==1.4.2
