apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: execute-script-template
  annotations:
    workflows.argoproj.io/description: |
      This workflow template provides an general template for running a script and is capable of artifact passing.
spec:
  entrypoint: execute-script
  templates:
  - name: execute-script
    
    inputs:
      parameters:
      - name: script-args
        default: ""
      - name: primary-input-blob-location
        default: ""
      - name: supplementary-input-blob-location
        default: ""
      - name: output-blob-location
        default: ""
      artifacts:
      - name: primary-input-artifact
        path: /tmp/input/primary/{{inputs.parameters.primary-input-blob-location}}
        optional: true
        s3:
          key: "{{inputs.parameters.primary-input-blob-location}}"
      - name: supplementary-input-artifact
        path: /tmp/input/supplementary/{{inputs.parameters.supplementary-input-blob-location}}
        optional: true
        s3:
          key: "{{inputs.parameters.supplementary-input-blob-location}}"

    container: 
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["{{inputs.parameters.script-args}}"]

    outputs:
      artifacts:
        - name: output-artifact
          path: /tmp/output
          archive:
            none: {}
          optional: true
          s3:
            key: "{{inputs.parameters.output-blob-location}}"
